name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10, 12, 14, 16]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache npm modules
        uses: actions/cache@v2
        env:
          cache-version: 1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ env.cache-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-${{ env.cache-version }}-
            ${{ runner.os }}-${{ matrix.node-version }}-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: (coverage) Install
        if: matrix.node >= 16
        run: yarn global add c8

      - name: Test
        if: matrix.node < 16
        run: yarn test

      - name: (coverage) Test
        if: matrix.node >= 16
        run: c8 --include=src yarn test

      - name: Check Types
        run: yarn typecheck

      - name: (coverage) Report
        if: matrix.node >= 16
        run: |-
          c8 report --reporter=text-lcov > coverage.lcov
          bash <(curl -s https://codecov.io/bash)
